### ISSUE TITLE
Love this!

### ISSUE THREAD

**Issue by cori** [tombarys/roam-depot-nautilus#1]
I have been waiting for this since I saw the first commit and am excited to give it a try!

Super useful so far (tho it's my first workday using it) - there are a couple of things that would make it even better. I might try to poke at some of these but realistically doubt i'll have enough time to make real progress.

1. Adjustable start and end times?
    1. I start my day typically around 0630 local time. It would be nice if the shell could start then

<img width="723" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/46317/90125aa1-eefe-483c-a2c0-a7583f298da1">

2. A way to mark an appointment as "free"
    1. I block my calendar with "Focus Time" blocks and i also show my partner's work schedule. It would be great if those could show in the nautilus for visibility but not block task placement
    2. might not be possible - i haven't read any of the code yet...

Thanks again for this!

**Comment by tombarys** [comment]
Hi, @cori, thanks for sharing!

The 1) is very high on my Nautilus todo-list (after squashing some bugs).

The 2) is a completely new idea I have never thought of but clever one ;) I will think about it; thank you very much for your feedback!

Tomáš

**Comment by tombarys** [comment]
Hi, @cori, it is possible to change the starting time now (just update in Roam Depot).

**Comment by DRschulman** [comment]
Agreed - THIS IS ABSOLUTELY FABULOUS!!!! THANK YOU!

**Comment by cori** [comment]
I tried updating my start tie to 6, but nautili still seem to be starting at 8.

i've deleted and re-added my DNP template that now includes the nautilus render code, but i'm not sure if that's a sufficiently "first added" event to trigger the new time. I'll give it a day or so to see if it corrects itself before digging in more deeply.

**Comment by tombarys** [comment]
@cori Try adding `{{[[roam/render]]:((roam-render-Nautilus-cljs)) 22 15 6}}` render code. The third parameter is the call for starting at 6. 

In general, removing and re-adding the plugin (and setting the right start in the Settings) should help. Feel free to ask if problem occurs again.

**Comment by tombarys** [comment]
If everything fails, try removing the plugin again via Roam Depot, then go to page **roam/render** and remove whole Nautilus block including children. Then install the plugin again. It should work again then.

**Comment by cori** [comment]
ok I've un-/re-installed a few times. When I went looking for the `roam/render` item I had a bit of trouble finding it the first time but that's probably a graph issue - my graph may be a little wonky because it's been imported from a backup and had some of its block-ids munged - long before i install Nautilus but might impact something about `roam/render`.

Anyway i found it __referenced__ on my `roam/render` page, and on the 2nd uninstall i wiped that, and on the third i haven't been able to find the render template yet - so that's probably related, and I'll go hunting to make sure i get rid of all of the render templates.

I've also tried with the direct params. None of these seem to adjust the start time.

Again I'll do some poking to make sure I don't have cruft laying about before i dig more deeply....

**Comment by cori** [comment]
this is probably user error - I have what seem to be a correctly-aligned Nautilus template, but when i insert my DNP template that _calls_ Nautilus it's still showing the std start time (sorry for the truncated screenshot - trying to keep it mostly private).

<img width="308" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/46317/6f13cbc4-9fd0-4756-8051-e8e7d2c09d1b">

When i go to my __template__ and delete the Nautilus line and then reinsert it as-is I get the same thing but when i replace the template call with the parameterized one you provided everything looks as expected, so I probably forgot something about how i placed it initially and just kept telling it to do the same wrong thing.

I think we can close this issue unless you're still contemplating free time blocks (which probably deserves it's own ticket if so :-) ). Thanks a ton!!

**Comment by cori** [comment]
hahaha ok i spoke too soon!

I have this in the presumably-Nautilus-created Nautilus render block, with this source `#worklog {{[[roam/render]]:((roam-render-Nautilus-cljs)) 22 15 6}}`

<img width="414" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/46317/07258ebf-775f-4a8c-bff6-f327508a3250">

My DNP "template" is a SmartBlock that has the now-updated parameterized render template that matches the one that (I think) Nautilus created on install (with the corrected params from my config: `{{[[roam/render]]:((roam-render-Nautilus-cljs)) 22 15 6}}`)

<img width="410" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/46317/6d1829be-ee90-4f64-9246-47e3a4815756">

but when i trigger the SmartBlock I get the correct parameterized version inserted `{{[[roam/render]]:((roam-render-Nautilus-cljs)) 22 15 6}}` but the Nautilus does not use those params as far as I can tell:

<img width="198" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/46317/bde3d93a-acca-43e5-9c96-0592f848b2a1">

mucking with the parameters seems to indicate that only the middle one has any effect here; `{{[[roam/render]]:((roam-render-Nautilus-cljs)) 5 30 7}}` results in 

<img width="240" alt="image" src="https://github.com/tombarys/roam-depot-nautilus/assets/46317/f06e9038-4e34-4501-96d1-123832706fed">

e.g. longer default timeblocks but no earlier start time or more truncated titles.

Probably still a graph problem, so any tips on where to look would be highly appreciated!

**Comment by cori** [comment]
heh ok it seems like if i update the inserted template i get the right start time - i think i'll wait and see what tomorrow brings before digging any more

**Comment by cori** [comment]
this morning everything seemed to work as expected with the new date, so I'm going to go ahead and close this.

Tomáš if you want an issue to track "free time" I'm happy to create a new one for that!

**Comment by tombarys** [comment]
Yes, cori, please, create an extra issue.
