### ISSUE TITLE
Change the start and end of a day

### ISSUE THREAD

**Issue by 101scholar** [tombarys/roam-depot-nautilus#3]
Currently a day starts from 8am and ends at 9pm. Can it be modified, say in the extreme case starting from 0:00 and ends at 23:59?

**Comment by tombarys** [comment]
Hi, Sean, a new version supporting workday starts 6am, 7am and 8am is in review. The problem is the visual simplicity that declines when morning and evening tasks start to overlap. Let me know after the update, how this new version worked for you. Thanks!

**Comment by 101scholar** [comment]
Thanks, I'll give it a try! Indeed in my case, I may get jet lag sometimes, so the working time can be a bit unusual.

**Comment by tombarys** [comment]
New option to change starting times is live in Roam Depot. Just update :)
